### ISSUE TITLE
Fabric REST API fails to bring up the API for the newly added organization

### ISSUE THREAD

**Issue by nithindj192** [Altoros/fabric-rest#1]
I am using [Altoros - Fabric Rest](https://github.com/Altoros/fabric-rest) to have API to Fabric network. When I am trying to add a new organization like [Adding an ORG to a channel](http://hyperledger-fabric.readthedocs.io/en/release-1.1/channel_update_tutorial.html), I am getting an error while bringing up the docker compose file of the new organization.

I checked the log, this what the error is. The REST API works fine for the organizations that already present in network.

_connect - timed out after:5000

api.ORG3.example.com | [2018-04-26 13:02:22.491] [ERROR] peer-listener - (((((((((((( Got block error )))))))))))

api.ORG3.example.com | [2018-04-26 13:02:22.492] [ERROR] peer-listener - Error: Unable to connect to the peer event hub

**Comment by MaxXx1313** [comment]
Hi
Make sure ORG3 section exists in network-config.json and have right peers address

**Comment by nithindj192** [comment]
ORG3 exists and I have checked the peer addresses, peer ports and peer certificates. I did log them on the peer listener file, all look good. Not getting why exactly it is failing. What else might be the issue?

**Comment by nithindj192** [comment]
Even though the network-config.json has been updated, the peers doesn't come up on the Info screen. But other updates like chain code comes up. Does that might be the issue? I am thinking once the REST API is up and running, it not picking the new updated network-config.json.

**Comment by MaxXx1313** [comment]
That 'a right, once network-config.json is changed, a picture server needs restarting

**Comment by nithindj192** [comment]
Is there any way to do this without restarting the server?

**Comment by MaxXx1313** [comment]
Not yet

**Comment by nithindj192** [comment]
Thanks for the help. Let me know if you have idea on how we can achieve without restarting.

**Comment by nithindj192** [comment]
One more question, I am still seeing the error even after restart. And I am seeing this error in both peers of the new Organization, **[gossip/service] updateAnchors -> ERRO 327 Tried joining channel mychannel but our org( org3), isn't among the orgs of the channel: [org1 org2] , aborting**. Can this be the cause of the error in API?

I have checked everything. network-config has data properly. The CAs and MSPs are proper. What are all the reasons possibly causing the error I mentioned above fr API? I am able to query using new organization peer in CLI. Any advice will be much appreciated.

**Comment by MaxXx1313** [comment]
@nithindj192 Thank you for the comment!

**Comment by sivachaitanya** [comment]
yeah not using the _/- or capital letters resolved this for me, Thanks for the great tool you guys
