### ISSUE TITLE
docker generates files to mapped volumes as root

### ISSUE THREAD

**Issue by olegabu** [Altoros/fabric-rest#7]
when using dockers to generate files onto mapped volumes they're owned by root and are not readable unless explicitly change ownership by
`sudo chown -R 1000:1000 artifacts/`
research how to do `docker-compose run` with the current user owning generated files

**Comment by MaxXx1313** [comment]
The files just disappearing from the `artifacts/crypto-config/ordererOrganizations` folder. I've run into it few times, but cannot reproduce anymore.
I think there may be no issue with access.
