### ISSUE TITLE
cannot start api-server docker outside of this repo

### ISSUE THREAD

**Issue by olegabu** [Altoros/fabric-rest#8]
if you copy the docker-compose.yaml into another project and hope it will pick up altoros/fabric-rest image and start it up it won't happen. Tried to recreate directory structure as close to fabric-rest but to no avail; placing artifacts/network-cofig-template, creating empty server directory, rebuilding don't help.
This is a blocker.

**Comment by olegabu** [comment]
[2017-07-27 20:25:25.085] [DEBUG] Socket - a new user connected: Arzqy7XojEskOx6WAAAA
api.a.nsd.ru      | [2017-07-27 20:25:47.636] [DEBUG] WebApp - End point : /users
api.a.nsd.ru      | [2017-07-27 20:25:47.636] [DEBUG] WebApp - User name : test
api.a.nsd.ru      | [2017-07-27 20:25:47.640] [DEBUG] fabric-client - [FileKeyValueStore.js]: FileKeyValueStore.js - constructor
api.a.nsd.ru      | [2017-07-27 20:25:47.642] [ERROR] Helper - Failed to get registered user: test, error: TypeError: Cannot read property 'setStateStore' of undefined
api.a.nsd.ru      |     at hfc.newDefaultKeyValueStore.then (/usr/src/app/app/helper.js:233:9)
api.a.nsd.ru      | Request failed: POST /users: TypeError: Cannot read property 'setStateStore' of undefined

**Comment by MaxXx1313** [comment]
fixed.
The reason is specific organisation name. Previously any organization name have to start with 'org'.
Now it's gone, but the same issue left for peer name: it should starts with 'peer'.
